# Generated by Django 5.1.6 on 2025-02-12 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_democlass_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
